spring.application.name=pinnel-api1

spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:h2:mem:pinnel;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.locations=classpath:db/migration/{vendor}

# ----------------------------------------------------------------------
# Pinnel application configuration (pinnel.*)
# ----------------------------------------------------------------------

pinnel.cities.search-limit=20
