CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cognito_id    VARCHAR(255) NOT NULL UNIQUE,
    email         VARCHAR(255) NOT NULL UNIQUE,
    username      VARCHAR(50)  NOT NULL,
    display_name  VARCHAR(100),
    bio           VARCHAR(500),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE cities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    country     VARCHAR(80)  NOT NULL,
    latitude    NUMERIC(9,6),
    longitude   NUMERIC(9,6),
    population  INTEGER,
    CONSTRAINT uk_cities_name_country UNIQUE (name, country)
);

CREATE TABLE pins (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(2000),
    latitude    NUMERIC(9,6) NOT NULL,
    longitude   NUMERIC(9,6) NOT NULL,
    is_public   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id     BIGINT,
    city_id     BIGINT NOT NULL,
    CONSTRAINT fk_pins_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_pins_city FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE RESTRICT,
    CONSTRAINT ck_pins_latitude  CHECK (latitude  BETWEEN -90  AND  90),
    CONSTRAINT ck_pins_longitude CHECK (longitude BETWEEN -180 AND 180)
);
CREATE INDEX ix_pins_city_id ON pins (city_id);
CREATE INDEX ix_pins_user_id ON pins (user_id);

CREATE TABLE trips (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120)  NOT NULL,
    budget        NUMERIC(12,2),
    country_names CHARACTER VARYING ARRAY NOT NULL DEFAULT ARRAY[],
    user_id       BIGINT NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_trips_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_trips_user_id ON trips (user_id);

CREATE TABLE trip_pins (
    trip_id BIGINT NOT NULL,
    pin_id  BIGINT NOT NULL,
    PRIMARY KEY (trip_id, pin_id),
    CONSTRAINT fk_trip_pins_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT fk_trip_pins_pin  FOREIGN KEY (pin_id)  REFERENCES pins  (id) ON DELETE CASCADE
);
CREATE INDEX ix_trip_pins_pin_id ON trip_pins (pin_id);
