ALTER TABLE trips ADD CONSTRAINT uk_trips_id_user UNIQUE (id, user_id);

CREATE TABLE trip_details (
    id         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id    BIGINT  NOT NULL,
    user_id    BIGINT  NOT NULL,
    visit_date DATE    NOT NULL,
    city_id    BIGINT  NOT NULL,
    city_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_trip_details_trip FOREIGN KEY (trip_id, user_id) REFERENCES trips (id, user_id) ON DELETE CASCADE,
    CONSTRAINT fk_trip_details_city FOREIGN KEY (city_id)          REFERENCES cities (id)         ON DELETE RESTRICT,
    CONSTRAINT uk_trip_details_id_user UNIQUE (id, user_id)
);
CREATE INDEX ix_trip_details_trip_id   ON trip_details (trip_id);
CREATE INDEX ix_trip_details_user_id   ON trip_details (user_id);
CREATE INDEX ix_trip_details_trip_date ON trip_details (trip_id, visit_date);

CREATE TABLE trip_detail_pins (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_detail_id BIGINT       NOT NULL,
    user_id        BIGINT       NOT NULL,
    pin_id         BIGINT       NOT NULL,
    pin_order      INTEGER      NOT NULL DEFAULT 0,
    visit_time     TIME,
    budget         NUMERIC(12,2),
    CONSTRAINT fk_trip_detail_pins_detail FOREIGN KEY (trip_detail_id, user_id) REFERENCES trip_details (id, user_id) ON DELETE CASCADE,
    CONSTRAINT fk_trip_detail_pins_pin    FOREIGN KEY (pin_id)                  REFERENCES pins         (id)         ON DELETE CASCADE,
    CONSTRAINT ck_trip_detail_pins_budget CHECK (budget >= 0)
);
CREATE INDEX ix_trip_detail_pins_detail_id ON trip_detail_pins (trip_detail_id);
CREATE INDEX ix_trip_detail_pins_user_id   ON trip_detail_pins (user_id);

DROP TABLE trip_day_pins;
DROP TABLE trip_day_cities;
DROP TABLE trip_days;
