CREATE TABLE trip_days (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id    BIGINT NOT NULL,
    visit_date DATE   NOT NULL,
    CONSTRAINT fk_trip_days_trip     FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT uk_trip_days_trip_date UNIQUE (trip_id, visit_date)
);
CREATE INDEX ix_trip_days_trip_id ON trip_days (trip_id);

CREATE TABLE trip_day_cities (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_day_id BIGINT  NOT NULL,
    city_id     BIGINT  NOT NULL,
    city_order  INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_trip_day_cities_day  FOREIGN KEY (trip_day_id) REFERENCES trip_days (id) ON DELETE CASCADE,
    CONSTRAINT fk_trip_day_cities_city FOREIGN KEY (city_id)     REFERENCES cities    (id) ON DELETE RESTRICT
);
CREATE INDEX ix_trip_day_cities_day_id ON trip_day_cities (trip_day_id);

CREATE TABLE trip_day_pins (
    id               BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_day_city_id BIGINT  NOT NULL,
    pin_id           BIGINT  NOT NULL,
    pin_order        INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_trip_day_pins_day_city FOREIGN KEY (trip_day_city_id) REFERENCES trip_day_cities (id) ON DELETE CASCADE,
    CONSTRAINT fk_trip_day_pins_pin      FOREIGN KEY (pin_id)           REFERENCES pins            (id) ON DELETE CASCADE
);
CREATE INDEX ix_trip_day_pins_day_city_id ON trip_day_pins (trip_day_city_id);
